config/routes.rb
Fb::Application.routes.draw do
	devise_for :users

	get "listings/detail" #simple get. Very basic output of the view...
	match "/:id" => "listings#index" #doesn't do anything currently, besides allow a param on the homepage...
	match "/listings/detail/:id" => "listings#detail"
	match "/listings/new/" => "listings#new"
	match "/listings/create/" => "listings#create" 
	
	resources :listings
	
	match "/listings/update_listing/" => "listings#update_listing"
	
	
	
	match "/posts/get_zones/:id" => "posts#get_zones"
	match "/posts/new_zone/" => "posts#new_zone"
	

  	get "home/index"

	
	
	
	
	resources :images #try this instead so the image upload form will output properly...
	match "upload" => "images#upload"
	match "accept" => "images#accept"
	match "reject" => "images#reject" 
	match "images/new/:id" => "images#create"
	match "images/new" => "images#create"
	match "images/delete/:id" => "images#delete"
	
	

  root :to => "listings#index"

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	has_many :images, :dependent => :destroy #Rails ActiveRecord Relation. Defined here instead of the DB. 1 post has many images.
	# accepts_nested_attributes_for :images # This allows us to access the images straight from the listing object like this: @listing.images. The :reject_if call makes sure that we do not store empty TripImage records – sometimes users will not add an image for the trip right away.
	# for a multi-model form, add this so you can edit the image from the listing form
	accepts_nested_attributes_for :images, :allow_destroy => :true, :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
	
	
	belongs_to :price #this is a one way, non-dependant relationship. If this is erased, we don't want that price range to be destroyed. Belongs to is used
					  #because the foreign key to price is in Listings table
	belongs_to :user #MUST be on separate lines			
					
	#belongs to 1 user... add this in later after we build the user tables...
	delegate :prince_range, :to => :price #makes .price_range available to listing. ie: listing.price_range. Very slick.
	
	# validation for stuff. This will make it fail currently. Adjust my code, so it doesn't save it at first...? ...?
	# validates :name,  :presence => true
	
	# def as_json()
	# 		super(:include => :price)
	# 	end

	#attr_accessible :id
	
	
	
	
	def price_range
	    price.price_range #fetches the price range as an attribute when I add it to the controller...
	end
	
	# so in the view you can call   if @listing.owned_by(current_user) 
	# this didn't seem to work... don't know why...
	def owned_by?(user)
    	user.id == self.user_id 
  	end
	
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	# redirect to signin if user is not authenticated on all listing controllers... No auth required for index, detail
	before_filter :authenticate_user!, :except => [:index, :detail, :create] #TODO remove :create from here?
	
	#require 'FileUtils' #for the delete folder action #breaks in staging
	
	
	def index
	
		
		@listings = Listing.all
		
		#@listings = Listing.find.includes(:prices).(:price_range => params[:id])  #not working quite yet
		

		respond_to do |format|
			format.html #index.html.erb
			format.xml { render :xml =>@listings }
		end
	end	

	# def detail
	# 		render :action => "detail" #render the detail view...?
	# 	end	

	# --------------------------------------------------------------------

	def detail 
		@listing = Listing.find(params[:id])  
		@image = Image.new #should this link somewhere else?

		respond_to do |format| 
			format.html # show.html.erb  
			format.xml { render :xml => @listing } 
		end 
	end 
	
	# --------------------------------------------------------------------
	
	def destroy 
		@listing = Listing.find(params[:id])  
		
		# if destroy was a success, remove the listing image folder
		if @listing.destroy 
			#require 'fileutils' # thought this was necessary, but it's not... The below delete still works, without the req...
			dir = Rails.root + '/system/photos/' + @listing.id.to_s()
			FileUtils.rm_rf(dir)	
			
		end	
		
		
		 

		respond_to do |format| 
			format.html { redirect_to(listings_url) } 
			format.xml { head :ok } 
		end 
	end 
	
	# --------------------------------------------------------------------
	
	def new
		# create a new listing, with a status of "draft"
		@listing = Listing.new(:price_id => 1)  # Default price id
		# save it to db
		# TODO add validation that it has to have a price ID, on record creation. So the view doesn't break.
		# @listing.save
		@image = Image.new

		# redirect_to "/detail/@listing.id"
		# redirect_to "/listings/detail/:id"
		
		respond_to do |format| 
			format.html # show.html.erb  
			format.xml { render :xml => @listing } 
		end
	end	
	
	# --------------------------------------------------------------------
	
	# TODO consider combining this one and create, and fork based on whether params are passed or not.
	def create
		# create a new listing and save it immediately. Assign it to guest, with a status of "draft"
		
		# if the user is singed in, attach the user_id to the params...
		if user_signed_in?
			params[:listing][:user_id] = current_user.id
		end
		
		# if the user isn't signed in, create a temp user? FIXME really think about this...
		
		
		
		@listing = Listing.new(params[:listing])  
		# save it to db
		# TODO add validation that it has to have a price ID, on record creation. So the view doesn't break.
		
		# @image = Image.new
		
		
		# on success, redirect to listing
		# if @listing.save
		# 			redirect_to "/detail/@listing.id"
		# 		else
		# 			redirect_to "/"
		# 		end
		#on failure... 
		
		# redirect_to "/listings/detail/:id"
		
		# process the file upload...
		
		
		
		respond_to do |format| 
			if @listing.save
			      format.html { redirect_to("/listings/detail/#{@listing.id}",
			                    :notice => 'Listing was successfully created.') }
			      format.xml  { render :xml => @listing,
			                    :status => :created, :location => @listing }
			    else
			      format.html { render :action => "new" }
			      format.xml  { render :xml => @listing.errors,
			                    :status => :unprocessable_entity }
			    end
		end
	end	

	
	# --------------------------------------------------------------------
	
	def update
		@listing = Listing.find(params[:listing][:id])
		
		#if params were passed in for updating
		if @listing.update_attributes(params[:listing])
	 	#should we return the whole thing or just what's needed?
			json_response = {
				"success" => @listing.save, #save to DB and assign true/false based on success...
				# "message" => @listing.attributes
				"message" => @listing.serializable_hash(:methods => [:price_range]) #calls the listing.price_range method defined in the model
				# "message" => @listing.as_json(:only => [:price], :include =>[:prices]) 
				# "message" => @listing.as_json
				# "message" => @listing.attributes.as_json(:include => [:price])
				
				#@listing.attributes #USE attributes to show output the content of the @message obj, and not another object called "message"
			}
			
			respond_to do |format| 
				#json response
				format.html { render:json => json_response }
					 
				format.xml { render :xml => @listing } 
				
				#normal response. Consider leaving this for now?
				#format.html { render :action => "detail" } #refresh this page, with new data in it. Consider trying to use redirect instead?
				#format.xml  { head :ok }
			end
		end #end if	
	
	 # respond_to do |format|
	 # 	    if @listing.update_attributes(params[:listing])
	 # 	      format.html { redirect_to(@listing,
	 # 	                    :notice => 'Post was successfully updated.') }
	 # 	      format.xml  { head :ok }
	 # 	    else
	 # 	      format.html { render :action => "edit" }
	 # 	      format.xml  { render :xml => @listing.errors,
	 # 	                    :status => :unprocessable_entity }
	 # 	    end
	 # 	  end
	
	
	end
	
	# --------------------------------------------------------------------
	
	
	


end

app/helpers/listings_helper.rb
module ListingsHelper
	#is the current user the owner of the listing?
	def isListingOwner?
		
	end	
	
end

app/views/listings/_edit_form.html.erb
<%
# this partial is for the edit / update photographer data, including the image updates, and detail updates...

%>
<!-- Photographer Data -->
<div class="append-bottom photo-data">
	<%= form_for @listing, :listing, :url => {:controller => "listings", :action => "update_listing" }, :html => {:class => "nifty_form", :id => "edit_listing_form"} do |f| %>
	
		<h3 id="edit_name" class="detail hide_on_edit-js"><%= @listing.name %></h3>
		<!-- Hidden form info -->
		<h3 class="detail show_on_edit-js hidden"><%= f.text_field :name %></h3>
		
		<div class="append-bottom hide_on_edit-js">
			in <span id="edit_city"><%= @listing.city %></span>, <span id="edit_state"><%= @listing.state %></span> <br />
			<span id="edit_price"><% @listing.price.price_range %></span>
		</div>
		
		<% if can? :update, @listing %>
		<!-- Hidden form info... Consider grouping these better? -->
		<div class="append-bottom show_on_edit-js hidden">
			in <%= f.text_field :city %>, <%= f.text_field :state %> <br />
			
			<%= collection_select(:listing, :price_id, Price.all, :id, :price_range) 
			#get the select from a collection. got this from rails guides. Awesome.
			 %>
			
		</div>
		<% end %>
	
		<p id="edit_description" class="append-bottom hide_on_edit-js"><%= @listing.description %></p>
		<% if can? :update, @listing %><p class="append-bottom show_on_edit-js hidden"><%= f.text_area :description, :rows => "7", :cols => "60" %></p><% end %>
	
		<div class="append-bottom hide_on_edit-js" id="contact_container">
			<h6>Contact Info:</h6>
			<p>
				<span id="edit_phone"><%= @listing.phone %></span><br />
				<span id="edit_email"><%= @listing.email %></span><br />
				<span id="edit_website"><%= @listing.website %></span>
			</p>
			<%# if user_signed_in? && current_user.id == @listing.user_id %>
			<% if can? :update, @listing %>
			<div class="append-bottom"><button type="button" class="edit_form">Edit this section</button></div>
			<% end %>
		</div>
	
		<%# consider moving this into the view helper? %>
		<%# if user is signed in AND authenticated as owner %>
		<% if can? :update, @listing %>
		<!-- Hidden contact info -->
		<div class="append-bottom show_on_edit-js hidden">
			<h6>Contact Info:</h6>
			<!-- Should we be using method:put when updating records? Don't think it's making a difference right now... -->
	
	
		<%# form_tag(:controller => "listings", :action => "update", :method => "get", :class => "nifty_form") do |f| %>
			<%= f.hidden_field :id %>
			<%= f.text_field :phone %><br />
			<%= f.text_field :email %><br />
			<%= f.text_field :website %><br />
			<%# f.text_area :email, :size => "60x12" %>
		
			<%# submit_tag "Save" %>
			<!-- this should probably be unobtrusive with a fallback if the JS isn't attached properly?	-->
			<button type="button" class="save">Save</button> <button type="button" class="cancel">Cancel</button> 
	
		</div>
		<% end %>
	
		<div>
			<h6>Reviews:</h6>
			<p>"Love this guy. He rocks. Great Customer Service." By johno. 4/5</p>
		</div>
	
	<% end %>
</div>              

<hr />

<!-- Output existing images -->
<% @listing.images.each do |image| %> 
	<% if defined?(image) %>
	<div id="comp_container" class="comp_container span-20 append-bottom">
		<!-- <img class="span-20 append-bottom" src="/images_user/<%# image.url %>" /> -->
		<%= image_tag image.photo.url(:medium) %>
		<p><%= image.description %> </p>
	</div>
	
		<% if can? :update, @listing %>
			<div class="span-10">
				Actions: <br /> 
				<%= form_for image, :url => image_url, :html => {:multipart => true, :id => "edit_images"} do |f| %>
					<%= f.hidden_field(:id) %><br />
					Replace Image and Description
					<%= f.file_field :photo %><br />
					<span class="span-5"><%= f.text_field :description %></span>
					
					<%= submit_tag "Upload" %> <br />
			
					<%# link_to 'Delete', image, :confirm => 'Are you sure?', :method => :delete, :class => "delete_image" %> <br />
					<button type="button" id="delete_<%= image.id %>" class="delete_image">Delete</button>
				<% end %>
			</div>
		<% end %>	
	<% end %>
<% end %>

<!-- Form for new images -->
<% if can? :update, @listing %>
<div class="span-20 append-bottom">
<!-- <%# form_for :image, @image, :url => image_path, :html => { :multipart => true } do |f| %> -->
<%= form_for @image, :url => "/images/new/#{@listing.id}" , :html => { :multipart => true } do |f| %>
    <%= f.text_field :description %><br />
	<%= f.file_field :photo %>
	<%= submit_tag "Upload" %>
  <% end %>
</div>
<% end %>

<br /><br />
<br /><br />
<div class="span-20 append-bottom hidden">
	<button>Contact Us</button> 
</div>


<%# debug(current_user.id)%>

app/views/listings/detail.html.erb
<% content_for :head do %>  
	<title>&mdash; Design Forum &mdash; </title> 
	
	<%= stylesheet_link_tag 'master' %> 
	
	
	
	
	<!-- YUI 3 Base. Host this locally?  -->
	<script type="text/javascript" src="http://yui.yahooapis.com/3.2.0/build/yui/yui-min.js"></script>
	
	<%= javascript_include_tag "detail_funcs" %>
	
	<!-- CSS 
	<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/combo?3.1.2/build/widget/assets/skins/sam/widget.css&3.1.2/build/widget/assets/skins/sam/widget-stack.css&3.1.2/build/overlay/assets/skins/sam/overlay.css">
	
	<script type="text/javascript" src="http://yui.yahooapis.com/combo?3.1.2/build/yui/yui-debug.js&3.1.2/build/oop/oop-debug.js&3.1.2/build/dom/dom-debug.js&3.1.2/build/event-custom/event-custom-debug.js&3.1.2/build/event/event-base-debug.js&3.1.2/build/pluginhost/pluginhost-debug.js&3.1.2/build/node/node-debug.js&3.1.2/build/event/event-delegate-debug.js&3.1.2/build/attribute/attribute-debug.js&3.1.2/build/base/base-debug.js&3.1.2/build/event/event-resize-debug.js&3.1.2/build/event/event-mouseenter-debug.js&3.1.2/build/dd/dd-debug.js&3.1.2/build/dump/dump-debug.js&3.1.2/build/json/json-debug.js&3.1.2/build/querystring/querystring-stringify-simple-debug.js&3.1.2/build/queue-promote/queue-promote-debug.js&3.1.2/build/datatype/datatype-xml-debug.js&3.1.2/build/io/io-debug.js&3.1.2/build/event/event-focus-debug.js&3.1.2/build/classnamemanager/classnamemanager-debug.js&3.1.2/build/widget/widget-debug.js&3.1.2/build/widget/widget-stdmod-debug.js&3.1.2/build/widget/widget-position-debug.js&3.1.2/build/widget/widget-position-align-debug.js&3.1.2/build/widget/widget-stack-debug.js&3.1.2/build/widget/widget-position-constrain-debug.js&3.1.2/build/overlay/overlay-debug.js&3.1.2/build/loader/loader-debug.js"></script>
	-->
	<!--<script type="text/javascript" src="/includes/detail_funcs.js"></script> -->
		
<% end %>


	<div id="actions_menu" class="append-bottom">
		<%= link_to "Back to all listings ", listings_path %> <!-- ||   <a id="toggleAllZonesLink" href="javascript:;">Toggle Overlays</a> | <a href="javascript:;" id="addCommentOverlayLink">Add Comment Overlay</a> | <a href="javascript:;" id="toggleAuthorComments">Toggle Author Comments</a>  <a href="javascript:;" onclick="document.getElementById('share_overlay').className='overlay_general'" style="float: right; margin-right: 10px;">Share this</a> -->  <!-- <a href="javascript:;" onclick="$('#area_1').show();">Add new comment zone</a> --> <!--  | <a href="#img">Skip to Image</a>  -->   <!-- Creates a new div. Positions it center somewhere. Add resizable and draggable to it. -->
	</div>
	
	
	
	<div id="header" class="container_16" style="">
		<!-- <a href="detail2_comments.php">Show Commments</a> -->
	</div>
	
	<div id="" class="notice_container">
		<% if flash[:notice] %>
			<p style="" class="content notice"><%= flash[:notice] %></p>
		<% end %>
	</div>	
	
	<div class="wrapper prepend-1">
	
		<%= render 'edit_form' %>
		
		<%# debug(@listing.attributes)%> 
	          
	</div><!-- /.wrapper -->
	
	
	
	
	<div id="footer" class="append-bottom span-20"></div> 

	<script type="text/javascript">
		//fb.init(<%# @post.images.first.post_id %>, "jamis"); 
		//fb.init(<?php echo $postData[0]->post_id;?>, "<?=$this->session->userdata('username'); ?>"); 
		//get getThreadData. Make this an ajax call...
		//fb.getThreadData(<?php echo $postData[0]->post_id;?>);
		
		//consider putting this in the JS itself?
		fb.init(); //load the YUI dependencies
		//fb.updateListing(document.getElementById("edit_listing_2"));
		//console.log(fb);
	</script>
	

app/views/listings/index.html.erb
	<% content_for :head do %>  
	<title>&mdash; Design Forum &mdash; </title>
	
	
	<%= stylesheet_link_tag 'master' %> 
	
	<%# javascript_include_tag :defaults %> <!-- necessary so delete link will work for now... Fix this later...-->
	
	
	
	<!-- JS Files Necessary for Fancybox -->
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script> 
	
	
	<script type="text/javascript">
		//externalize this, or put in on the server side...
		function splitUserData(str){
			var splitArray = str.split("_");
			$('#userName').val( splitArray[0] );
			$('#userID').val( splitArray[1] );
		}
	</script>
	<% end %>
	
	<div id="wrapper">
		<div id="header" class="span-14 prepend-1" style="margin-bottom: 40px; padding-top: 35px;">
			<%# link_to "Upload a new Comp", upload_path %>  
	
			<div class="span-15 append-bottom">
				<div class="span-10">
				<% if user_signed_in? %>
			    	Signed in as <%= current_user.email %>. Not you?
			    	<%= link_to "Sign out", destroy_user_session_path %>
			 	<% else %>
			    	<%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
			  	<% end %>
				</div>
		
				<!-- <button class="fr span-4" onclick="document.location = '<%=new_listing_path %>'">Create Listing</button> -->
				<%= button_to "Create Listing", new_listing_path, :class => "fr span-4" %>
			
			</div>
		
			<div>
			
				<h3>Find a photographer ...</h3>
				
				<div class="span-15">
					in San Antonio, TX, for
					<select name="some_name" id="some_name" onchange="" size="1" class="">
						<option value="option1">$100 &ndash; $500</option>
						<option value="option1">$500 &ndash; $1,000</option>
						<option value="option1">$1,000 &ndash; $5,000</option>
				
					</select>
				
					<button>Go</button>
				</div>	
			</div>
		</div>
	                
	
		<div id="content" class="span-14 prepend-1 clearfix" style="padding-top: 15px;">
			<!-- How do we test for an attached object of "images"? -->
		
			<% if defined?(@listings) %>
				<%# debug(@listings[1].images) %>
			<% end %>
		
		
		
				<% @listings.each do |listing| %> 
					<% if defined?(listing.images) %>
					<a class="listing_preview" href="<%= listings_detail_path + "/" + listing.id.to_s %>"> 
					<div id="" class="span-4">
						
						<h3><%= listing.name %></h3>
						<div class="append-bottom">
							in <%= listing.city %>, <%= listing.state %> <br />
							<%  listing.price.price_range %>
						</div>
						<%# image_tag "/images_user/" + listing.images.first.url %> 
						<% if defined?(listing.images.first.photo) %>
						<%= image_tag listing.images.first.photo.url(:small), :class => "span-4" %>
						<% end %>
						
						<br />
						<button onclick="document.location = '<%= listings_detail_path + "/" + listing.id.to_s %>'"><%= listing.name %></button>
						<br />
					
						Rating: 4/5 stars <br />
						Specialty: Weddings
						<br /><br /><br />
						<%= button_to 'Delete', listing, :method => :delete %> 
						<%# link_to 'Delete', listing, :method => :delete %>
					
					
						<br /><br />
						<!-- <%= link_to "Link back to this page... ", listings_path %> -->
		
					</div> <!-- /.span-4 -->
					</a>
					<% end %>
				<% end %>
		
			
	
		</div><!-- /#content -->
	
		<div class="span-12">
			<%# debug(@listings[0].images[2]) %>
		</div>                
	
		<div id="footer" class="container_16"><%= flash[@notice] %></div>
	
	</div> <!-- /#wrapper -->
	

app/views/listings/new.html.erb
<% content_for :head do %>  
	<title>&mdash; Design Forum &mdash; </title> 
	
	<%= stylesheet_link_tag 'master' %> 
	<%= stylesheet_link_tag 'forms' %> 
	
	
	
	<!-- YUI 3 Base. Host this locally?  -->
	<script type="text/javascript" src="http://yui.yahooapis.com/3.2.0/build/yui/yui-min.js"></script>
	
	<%= javascript_include_tag "detail_funcs" %>
	
	<!-- CSS 
	<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/combo?3.1.2/build/widget/assets/skins/sam/widget.css&3.1.2/build/widget/assets/skins/sam/widget-stack.css&3.1.2/build/overlay/assets/skins/sam/overlay.css">
	
	<script type="text/javascript" src="http://yui.yahooapis.com/combo?3.1.2/build/yui/yui-debug.js&3.1.2/build/oop/oop-debug.js&3.1.2/build/dom/dom-debug.js&3.1.2/build/event-custom/event-custom-debug.js&3.1.2/build/event/event-base-debug.js&3.1.2/build/pluginhost/pluginhost-debug.js&3.1.2/build/node/node-debug.js&3.1.2/build/event/event-delegate-debug.js&3.1.2/build/attribute/attribute-debug.js&3.1.2/build/base/base-debug.js&3.1.2/build/event/event-resize-debug.js&3.1.2/build/event/event-mouseenter-debug.js&3.1.2/build/dd/dd-debug.js&3.1.2/build/dump/dump-debug.js&3.1.2/build/json/json-debug.js&3.1.2/build/querystring/querystring-stringify-simple-debug.js&3.1.2/build/queue-promote/queue-promote-debug.js&3.1.2/build/datatype/datatype-xml-debug.js&3.1.2/build/io/io-debug.js&3.1.2/build/event/event-focus-debug.js&3.1.2/build/classnamemanager/classnamemanager-debug.js&3.1.2/build/widget/widget-debug.js&3.1.2/build/widget/widget-stdmod-debug.js&3.1.2/build/widget/widget-position-debug.js&3.1.2/build/widget/widget-position-align-debug.js&3.1.2/build/widget/widget-stack-debug.js&3.1.2/build/widget/widget-position-constrain-debug.js&3.1.2/build/overlay/overlay-debug.js&3.1.2/build/loader/loader-debug.js"></script>
	-->
	<!--<script type="text/javascript" src="/includes/detail_funcs.js"></script> -->
		
<% end %>


	<div id="actions_menu" class="append-bottom">
		<%= link_to "Back to all listings ", listings_path %> <!-- ||   <a id="toggleAllZonesLink" href="javascript:;">Toggle Overlays</a> | <a href="javascript:;" id="addCommentOverlayLink">Add Comment Overlay</a> | <a href="javascript:;" id="toggleAuthorComments">Toggle Author Comments</a>  <a href="javascript:;" onclick="document.getElementById('share_overlay').className='overlay_general'" style="float: right; margin-right: 10px;">Share this</a> -->  <!-- <a href="javascript:;" onclick="$('#area_1').show();">Add new comment zone</a> --> <!--  | <a href="#img">Skip to Image</a>  -->   <!-- Creates a new div. Positions it center somewhere. Add resizable and draggable to it. -->
	</div>
	
	
	
	<div id="header" class="container_16" style="">
		<!-- <a href="detail2_comments.php">Show Commments</a> -->
	</div>
	
	<div class="wrapper prepend-1">
	
		<%# create new image so it's ready in the form %>
		<% @listing.images.build %>
		<%= form_for @listing, :listing, :url => {:controller => "listings", :action => "create" }, :html => {:class => "nifty_form", :id => "edit_listing_form", :multipart => true} do |listing_form| %>
		
			<fieldset id="" class="">
				<legend>Contact Details</legend>
				
				<p>
					<%= listing_form.label(:name, "Name:") %><br />
					<%= listing_form.text_field :name, :placeholder => "Company or personal name" %>
				</p>
				
				<p>
					<%= listing_form.label(:city, "City:") %><br />
					<%= listing_form.text_field :city, :placeholder => "What City do you live in?" %>
				</p>
				
				<p>
					<%= listing_form.label(:state, "State:") %><br />
					<%= listing_form.text_field :state, :placeholder => "What state do you live in" %>
				</p>
				
				<p>
					<%= listing_form.label(:price_range, "Price Range:") %><br />
					<%= collection_select(:listing, :price_id, Price.all, :id, :price_range) 
					#get the select from a collection. got this from rails guides. Awesome.
					 %>
				</p>
				
				<p>
					<%= listing_form.label(:description, "Description:") %><br />
					<%= listing_form.text_area :description, :rows => "7", :cols => "60", :placeholder => "Describe yourself and your company" %>
				</p>
				
				<p>
					<%# listing_form.hidden_field :id %>
					<%= listing_form.label(:phone, "Phone:") %><br />
					<%= listing_form.text_field :phone %><br />
					<%= listing_form.label(:email, "E-mail:") %><br />
					<%= listing_form.text_field :email %><br />
					<%= listing_form.label(:website, "Website:") %><br />
					<%= listing_form.text_field :website, :placeholder => "www.johnsphotos.com" %><br />
				</p>
			</fieldset>
		
			<fieldset id="" class="">
				<legend>Images</legend>
				<%= render :partial => 'images/form', :locals => {:form => listing_form} %>
				
				
				
				<%# form_for @image, :url => "/images/new/#{@listing.id}" , :html => { :multipart => true } do |f| %>
				<p>    
					<%# f.label(:description, "Image Description:") %><br />
					<%# f.text_field :description %><br />
					
					<%# f.file_field :photo %>
				</p>	
					<%# submit_tag "Upload" %>
				<%# end %>
				
			</fieldset>	
		
			<%= submit_tag "Create Listing", :style => "margin-bottom: 250px;" %>
			
		<% end %>
	
		<!-- Form Content start -->
		<!-- <input type="text" name="title" value="" id="title"> -->
		
		
		
		
		<%# debug(@listing.attributes)%> 
		
		
	          
		<!-- Form Content END -->
	
	</div><!-- /.wrapper -->
	
	
	
	
	<div id="footer" class="append-bottom span-20"></div> 

	<script type="text/javascript">
		//fb.init(<%# @post.images.first.post_id %>, "jamis"); 
		//fb.init(<?php echo $postData[0]->post_id;?>, "<?=$this->session->userdata('username'); ?>"); 
		//get getThreadData. Make this an ajax call...
		//fb.getThreadData(<?php echo $postData[0]->post_id;?>);
		
		//consider putting this in the JS itself?
		fb.init(); //load the YUI dependencies
		//fb.updateListing(document.getElementById("edit_listing_2"));
		//console.log(fb);
	</script>
	