config/routes.rb
Fb::Application.routes.draw do
	devise_for :users

	get "listings/detail" #simple get. Very basic output of the view...
	match "/:id" => "listings#index" #doesn't do anything currently, besides allow a param on the homepage...
	match "/listings/detail/:id" => "listings#detail"
	match "/listings/new/" => "listings#new"
	match "/listings/create/" => "listings#create" 
	
	resources :listings
	
	match "/listings/update_listing/" => "listings#update_listing"
	
	
	
	match "/posts/get_zones/:id" => "posts#get_zones"
	match "/posts/new_zone/" => "posts#new_zone"
	

  	get "home/index"

	
	
	
	
	resources :images #try this instead so the image upload form will output properly...
	match "upload" => "images#upload"
	match "accept" => "images#accept"
	match "reject" => "images#reject" 
	match "images/new/:id" => "images#create"
	match "images/new" => "images#create"
	match "images/delete/:id" => "images#delete"
	
	

  root :to => "listings#index"

end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :listing #Rails ActiveRecord Relation. An image belongs to a post. 

	# paperclip data
	has_attached_file :photo, :styles => { :medium => "700x700>", :small => "300x300>", :thumb => "100x100>" }, 
	:url => "/system/:attachment/:listing_id/:id/:style_:filename"#, #location where to output the server. :LISTING_ID is defined in config/initializers/paperclib.rb
	
	attr_accessible :photo, :description, :listing_id # what does this do?
	
	#:path => ":rails_root/public/system/:attachment/:id/:style/:basename.:extension" #location where to save the file
	#these styles can be retrieved as params like so "<%= image_tag image.photo.url(:medium) %>"

	# http://robots.thoughtbot.com/post/159807063/paperclip-tips-and-updates Blog post on how to pass data to it
	
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	
	def index
		upload #call the upload function
	end	
	
	#use this one? Just leave it for now... automatically looks for the upload view.
	def upload
		@image = Image.new(params[:image])
		
		# @image = Image.new 
		@message = "testing"
	end
	
	# def create
	# 		do_upload #consider just adding the route instead of doing it this way...?
	# 	end	
	
	def create
		# TODO validate that they are admin, and have rights to create an image...
		# TODO validate that they have rights to change the listing_id...
		
		#add listing_id param to it, so it's not saved on the page? OR just put in the form on the page to make it easy
	
		#append the id that was passed in as the parent listing id
		listing_id = params[:id]
		params[:image][:listing_id] = listing_id	
		
	    @image = Image.create( params[:image] )
		#@image.save #save the newly created image
		
		if @image.save
		      redirect_to("/listings/detail/#{listing_id}", :notice => 'Image was successfully updated.')
		end
		
		#if # @image.save
		 # 			format.html { redirect_to("/listings/detail/#{listing_id}",
		 # 	                    :notice => 'Listing was successfully updated.') }
		 # 	    	format.xml  { render :xml => @image,
		 # 	                    :status => :created, :location => @image }
	    # else
	    # 	    	format.html { render :action => "new" }
	    # 	    	format.xml  { render :xml => @listing.errors,
	    # 	                    :status => :unprocessable_entity }
	    # 	    end
		
		# respond_to do |format|
		# 			format.html #index.html.erb
		# 			format.xml { render :xml =>@image }
		# 		end
	end
	
	
	def update
	
		@image = Image.find(params[:image][:id])
		# replace the current image attachment with a new one...
		
		listing_id = @image.listing_id
		
		if @image.update_attributes(params[:image])
			notice = 'Image was successfully updated.'
		else
			notice = 'There was a problem updating your image'
		end		
		
		redirect_to("/listings/detail/#{listing_id}", :notice => notice)
		
		
		# at some point, do JSON. For now, just refresh the page...
		# json_response = {
		# 			"success" => @image.update_attributes(params[:image]), #save to DB and assign true/false based on success... This will update the attachment
		# 			"message" => "" #return a message if it fails... Figure out how to do this...
		# 		}
		# 		
		# 		respond_to do |format| 
		# 			#json response
		# 			format.html { render:json => json_response }
		# 				 
		# 			format.xml { render :xml => @image } 
		# 		end
	end	
	
	def delete
		@image = Image.find(params[:id]) #find image
		 
		# remove attachment, then image model
		@image.update_attribute(:photo, nil)
		
		#how can we make this fail gracefully and return the response properly?
		
		# TODO check for the existince of the image and return something based on that...
		
		json_response = {
			"success" => @image.delete, #save to DB and assign true/false based on success...
			"message" => "" #return a message if it fails... Figure out how to do this...
		}
		
		respond_to do |format| 
			#json response
			format.html { render:json => json_response }
				 
			format.xml { render :xml => @image } 
		end
	end	
	
	#should this be renamed to create?
	# def create
	# 	   	@image = Image.new( :listing_id => params[:id], :photo_file_name => params[:image][:photo], :description => params[:image][:description]) #params[:image]
	# 		
	# 		# what part of this should paperclip be handling?
	# 		@image.save
	# 		#redirect_to listing_url(@image)
	# 	end
	
	
	
	# def create 
	# 		#currently works... Extend this some more...
	# 		uploaded_io = params[:image][:url] 
	# 		File.open(Rails.root.join('public', 'images_user', uploaded_io.original_filename), 'w') do |file| #uploaded_io.original_filename is the param for the new filename to be saved.
	# 			file.write(uploaded_io.read)
	# 			@message = puts YAML::dump(file)
	# 		end 
	# 		
	# 		#image.new calls creates it in the DB. We have to pass it params...
	# 		#@image = Image.new(params[:image])  #call the new method...? How do we pass the params...?
	# 		@image = Image.new(:url => uploaded_io.original_filename) #we could either pass it in like this 1by1, or an array of params[]
	# 			
	# 		#@message = @image
	# 		#@message = "testing this message right here"
	# 
	# 		#we need to pass the image params back with it here...
	# 		render :action => "upload" #using render just loads the view, doesn't run through the upload function and actions... 
	# 		#redirect_to(upload_url)
	# 		#redirect_to image_url(@image_file) #pass it a param...
	# 			
	# 		
	# 	end 
	
	#from the tutorial. Not working so far.
	def do_upload
	  @image = Image.new(params[:image])
	  #if @image.save
	    #flash[:notice] = 'Image was successfully created.' #figure this one out later. FIXME Figure out how to send messages to 
	    redirect_to posts_url(@image)     
	  #else
	   # render :action => :index
	  #end
	end
	
	#accept image (add to db, leave on harddisk. Move if necessary.) Attach this to a new post also? Pass a post id, and create if not existent yet.
	def accept
		#create a new image obj, or take the one that was already created? Attach it to a post...
		@post = Post.new() #SHOULD this really be here...?
		@post.save
		#FIXME: for now, just have the post_id be put for the new post that was just created. Later be able to assign it better and check for success better. 
		@image = Image.new(:url => params[:url], :post_id => @post.id) #we could either pass it in like this 1by1, or an array of params[]
	
		
		respond_to do |format| 
			#if save to DB has been made
			if @image.save
				format.html { redirect_to(posts_path,  
					:notice => 'Post was successfully created.') } 
				format.xml { render :xml => posts_path,  
					:status => :created, :location => @post } 
			else  
				format.html { render :action => "new" } 
				format.xml { render :xml => @image.errors,  
					:status => :unprocessable_entity } 
			end  
		end 
	end
	
	#reject image (delete from file and DB)
	def reject
		#delete file...
		File.delete( Rails.root.join('public', 'images_user', params[:url]) )
		respond_to do |format|
			format.html { redirect_to(posts_path,  
				:notice => 'Image successfully deleted') }
		end	
		
	end		
	
	# def create
	# 		@image_file = Image.new(params[:image])
	# 		if @image_file.save
	# 			flash[:notice] = 'Attachment was successfully created.'
	# 			redirect_to image_url(@image_file)     
	# 		else
	# 			render :action => :new
	# 		end
	# 	end
	
	#not being used currently?
	def create_image 
		@image = Image.new 
		
		respond_to do |format| 
			redirect_to(posts_url)
		end 
	end 
	
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%# This partial will be rendered on the listings/new page. %>
<%= form.fields_for :images do |image_form| %>
	<p>    
		<%= image_form.label(:description, "Image Description:") %><br />
		<%= image_form.text_field :description %><br />
		
		<%= image_form.file_field :photo %>
	</p>

	<% unless image_form.object.nil? || image_form.object.new_record? %>
		<div class="field">
			<%= image_form.label :_destroy, 'Remove:' %>
			<%= image_form.check_box :_destroy %>
		</div>
	<% end %>
<% end %>

app/views/images/create.html.erb
<% content_for :head do %>  
<title>&mdash; Design Forum &mdash; </title>


<%= stylesheet_link_tag 'master' %> 

<%# javascript_include_tag :defaults %> <!-- necessary so delete link will work for now... Fix this later...-->



<!-- JS Files Necessary for Fancybox -->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script> 


<script type="text/javascript">
	//externalize this, or put in on the server side...
	function splitUserData(str){
		var splitArray = str.split("_");
		$('#userName').val( splitArray[0] );
		$('#userID').val( splitArray[1] );
	}
</script>
<% end %>


<div id="header" class="span-24 prepend-1" style="margin-bottom: 40px; padding-top: 35px;">
	
	
	
</div>
                

<div id="content" class="span-24 prepend-1 clearfix" style="padding-top: 15px;">
	<!-- How do we test for an attached object of "images"? -->
	
	
	
	
		<%# @image.each do |image| %> 
			<%# if defined?(listing.images) %>
			<div id="" class="span-7 ">
				<a id="inline" href="<%# listings_detail_path + "/" + listing.id.to_s %>"> 
				<h3><%# listing.name %></h3>
				<div class="append-bottom">
					in <%# listing.city %>, <%# listing.state %> <br />
					<%# listing.price.price_range %>
				</div>
				<%# image_tag "/images_user/" + listing.images.first.url %> </a>
				<%= image_tag @image.photo.url(:medium) %>
				<!--
				Rating: 4/5 stars <br />
				Specialty: Weddings
				<br /><br /><br />
				<%# button_to 'Delete', listing, :method => :delete %> 
				<%# link_to 'Delete', listing, :method => :delete %>
				-->
				
				<br /><br />
				<!-- <%= link_to "Link back to this page... ", listings_path %> -->
	
			</div>
			<%# end %>
		<%# end %>
	
		

</div><!-- /#content -->

<div class="span-12">
	<%# debug(@image.photo.attributes) %>
</div>                

<div id="footer" class="container_16"><%= flash[@notice] %></div>

app/views/images/upload.html.erb
	<% content_for :head do %>  
	<title>&mdash; Image Upload &mdash; </title>
	
	
	<%= stylesheet_link_tag 'master' %> 
	
	<%= javascript_include_tag :defaults %> <!-- necessary so delete link will work for now... Fix this later...-->
	<%= javascript_include_tag 'detail_funcs' %> 
	
	
	<% end %>
	

	<!-- Image placeholder -->
	<div class="" style="height: 400px; width: 500px; background-color: #747474; border: 2px solid #eee; float: left; margin-right: 20px;">

			<% if @image.url != nil  %> <!-- Because only 1 image is returned, use .url directly because it's not an array... -->
				<img id="newImg" width="500px" src="/images_user/<%= @image.url %>"  /> <!-- this should be prepped in the controller. I don't like having to do this manually... -->
				
				<!-- Show this when there is a thumbnail to show... -->
				<!-- <img id="newImg" width="200px" src="/images_user/<%= @image.url %>"  /> --> 
			<% end %>
			
			
		
			<!-- <img id="newImg" src="" /> -->
		

		<div style="color: #fff; text-align: center; margin-top: 155px;">Image Preview</div>
	</div>
	
	<!-- <%= form_for :image, @image, :url => { :action => "create" }, :html => {:class => "nifty_form", :multipart => true} do |f| %> 
	 
		<%= f.file_field :url %> <br />
		<%= submit_tag("Upload") %> 
	<% end %> 
	-->
	<br /><br /> 
	
	
	<h3>This one works:</h3>
	<!-- WORKING one. -->
	<%= form_for @image, :html => {:multipart => true} do |f| %>  
		<%= f.file_field :url %> <br />
		<%= submit_tag("Upload") %>
	<% end %> 
	
	
	<br /><br />
	<p><%= link_to "Back to Posts", posts_path %></p>

	<br /><br />
	
	<!-- For attachment fu. Currently broken.	-->
	<!--
	<h3>Proper Library one here:</h3>
	
	<%= form_for @image, :html => {:multipart => true} do |f| %>  
	  <p>
	    <label for="mugshot">Upload An Image:</label><br />
	    <%= f.file_field :uploaded_data %>
	  </p>
	  <p>
	    <%= submit_tag 'Upload' %>
	  </p>
	<% end -%>
	-->



	<div id="messages">
		Delete outcome or other messages here...
	</div>
	<!-- There must be a better way to test this -->
	<% if @image.url != nil  %>
	<!-- Should we just add it to the DB already, and then the accept here just redirects, and reject removes it?. Not sure... -->
	<div style="margin-left:586px; margin-top:159px;">
		<!-- Accept Image, Could make this one simply too... ? -->
		<%= form_for :image, @image, :url => { :action => "accept" }, :html => {:class => "nifty_form", :multipart => true} do |f| %> 
			 
			<%= hidden_field_tag(:url, @image.url) %> 
			<%= hidden_field_tag(:post_id, 2) %> 
			<%= submit_tag("Accept") %>
		<% end %>
		
		<!-- Reject Image-->
		<%# button_to "Reject", reject_path + "/" + @image.url %> 
		<%= form_for :image, @image, :url => { :action => "reject" }, :html => {:class => "nifty_form", :multipart => true} do |f| %> 
			 
			<%= hidden_field_tag(:url, @image.url) %> 
			<%= submit_tag("Reject") %>
		<% end %>
		
		
	</div> 
	<% end %>
	
	<!-- Message:<br /> -->
	<%# debug(@message) %>
	
	